project:
  type: website

website:
  title: "Rachel Jihyun Ki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Work Experience
      - href: projects.qmd
        text: Projects
      - href: personal.qmd
        text: Personal Life
  page-footer:
    right: "&copy; 2024, Rachel Jihyun Ki"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

